name: Auto Update

on:
  schedule:
    - cron: '0 3 * * *'  # Запуск каждый день в 03:00 UTC
  push:
    branches:
      - main  # Или укажите вашу основную ветку, если она называется иначе

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync"
          git push origin main
